apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: {{ .Values.global.appName }}
    tier: backend
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.global.appName }}
      tier: backend
  template:
    metadata:
      labels:
        app: {{ .Values.global.appName }}
        tier: backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          ports:
            - containerPort: {{ .Values.backend.containerPort }}
