apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: {{ .Values.global.appName }}
    tier: frontend
spec:
  type: NodePort
  ports:
    - port: {{ .Values.frontend.servicePort }}
      targetPort: {{ .Values.frontend.containerPort }}
      nodePort: {{ .Values.frontend.nodePort }}
  selector:
    app: {{ .Values.global.appName }}
    tier: frontend
