apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: {{ .Values.global.appName }}
    tier: backend
spec:
  type: NodePort
  ports:
    - port: {{ .Values.backend.servicePort }}
      targetPort: {{ .Values.backend.containerPort }}
      nodePort: {{ .Values.backend.nodePort }}
  selector:
    app: {{ .Values.global.appName }}
    tier: backend
